# Generated by Django 5.2.2 on 2025-06-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(help_text='Nombre completo del cliente', max_length=255)),
                ('correo_electronico', models.EmailField(help_text='Correo electrónico del cliente', max_length=254)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción corta o anotaciones sobre la factura')),
                ('documento', models.FileField(help_text='Archivo de la factura (PDF, JPG, PNG, ...)', upload_to='facturas/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
