# Generated by Django 5.0.2 on 2025-06-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisionAI', '0002_remove_factura_documento_documentofactura'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='resumen_excel',
            field=models.FileField(blank=True, help_text='Archivo Excel con los datos extraídos de la factura', null=True, upload_to='resumenes/'),
        ),
    ]
