services:
  db:
    image: postgres:17.5-alpine
    env_file: .envs/.env_postgres
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
#      interval: 5s
#      timeout: 5s
#      retries: 5

  web:
    build: ./src
    container_name: django_app
    image: registry.digitalocean.com/cualquiera/django:4
    platform: linux/amd64
    restart: always
    depends_on:
      - db
    env_file: .envs/.env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    command: python manage.py runserver 0.0.0.0:8000
