version: '3.8'

services:
  # ---------------------------------------------------
  # 1) Servicio PostgreSQL
  # ---------------------------------------------------
  db:
    image: postgres:14-alpine
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend-network

  # ---------------------------------------------------
  # 2) Servicio Django (backend)
  # ---------------------------------------------------
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      # En tu settings.py define DATABASES['default']['HOST'] = os.getenv('DB_HOST')
      DB_HOST: db
    ports:
      - "8000:8000"
    volumes:
      # ===> Aquí montamos la carpeta raíz completa en /app <===
      - .:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    networks:
      - backend-network

volumes:
  postgres_data:

networks:
  backend-network:
